In [5]:
# 25 rows and 4 columns
import numpy as np
import pandas as pd
matrix_data = np.random.randint(1,100,100).reshape(25,4)
column_headings = ['W','X','Y','Z']
df = pd.DataFrame(data=matrix_data,columns=column_headings)

In [6]:
df.head()

    W   X   Y   Z
0  45  20  46  15
1  57  60  88  40
2  80  93  92  24
3  77  25  43  37
4  11  82  36  92

In [7]:
df.head(8)

    W   X   Y   Z
0  45  20  46  15
1  57  60  88  40
2  80  93  92  24
3  77  25  43  37
4  11  82  36  92
5  88  97  52  24
6   8  29  47  22
7  45  21   2  75

In [8]:
df.tail(10)

     W   X   Y   Z
15  94  63  95  42
16  94  53  71  19
17   7  98  52  98
18   5  61  48  36
19  51  92  64  87
20  23  83  74  69
21  59  36  23  87
22  36  60  83  98
23  98  35  60  34
24  67  45  54  30