## DSC540-T301 Data Preparation (2265-1)

Weeks 7 and 8 Assignments

Due on 5/11/2026

Paula Iman

References:
McKinney, W. (2022). Python for data analysis: Data wrangling with pandas, NumPy, and Jupyter (3rd ed.). O'Reilly Media, Inc.

Lipp, B., Roychowdhury, S., & Sarkar, T. (2020). The data wrangling workshop (2nd ed.). Packt Publishing Ltd. McKinney, W. (2022). Python for data analysis: Data wrangling with pandas, NumPy, and Jupyter (3rd ed.). O'Reilly Media, Inc.

Data from GitHub. The Metropolitan Museum of Art Open Access CSV: https://github.com/metmuseum/openaccess/

### Chapter 7

1. Filter out missing data  
2. Fill in missing data   
3. Discretization and Binning

In [55]:
import pandas as pandas
import numpy as np
import os

In [56]:
file_path = r"D:\BU_Master\DSC540_Data_Preparation\MetObjects.csv"
# Loading a subset to see data and test
met_df = pd.read_csv(file_path, nrows=500, low_memory=False)
met_df.head()

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,River,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979.0,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980.0,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/3,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
3,67.265.10,False,False,False,4,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/4,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
4,67.265.11,False,False,False,5,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/5,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN

In [57]:
met_df.shape

(500, 54)

1. Filtering out missing data

In [58]:
# Dropping rows with any NaN values and seeing the shape
met_df_clean = met_df.dropna()
met_df_clean.shape

(0, 54)

In [59]:
# Since all the rows have some missing data, I will see which columns I should choose to have some data left after dropping NaN values.
print(met_df.isnull().sum())

Object Number                0
Is Highlight                 0
Is Timeline Work             0
Is Public Domain             0
Object ID                    0
Gallery Number             166
Department                   0
AccessionYear                6
Object Name                  0
Title                        0
Culture                    131
Period                     500
Dynasty                    500
Reign                      500
Portfolio                  500
Constituent ID             252
Artist Role                252
Artist Prefix              252
Artist Display Name        252
Artist Display Bio         252
Artist Suffix              252
Artist Alpha Sort          252
Artist Nationality         252
Artist Begin Date          252
Artist End Date            252
Artist Gender              470
Artist ULAN URL            341
Artist Wikidata URL        356
Object Date                  0
Object Begin Date            0
Object End Date              0
Medium                       0
Dimensions                   0
Credit Line                  0
Geography Type              78
City                       260
State                      469
County                     469
Country                     78
Region                     488
Subregion                  500
Locale                     500
Locus                      500
Excavation                 500
River                      500
Classification             500
Rights and Reproduction    495
Link Resource                0
Object Wikidata URL        152
Metadata Date              500
Repository                   0
Tags                       386
Tags AAT URL               386
Tags Wikidata URL          386
dtype: int64

In [60]:
# I will choose columns Object ID, Title, Culture, Object Date, and Country.
columns_to_keep = ['Object ID', 'Title', 'Culture', 'Object Date', 'Country']
subset_df = met_df[columns_to_keep]
print(f"Data frame shape is {subset_df.shape}")

Data frame shape is (500, 5)

In [61]:
# Using this data frame to delete NaN
cleaned_df = subset_df.dropna()
print(f"Cleaned data frame shape is {cleaned_df.shape}")

Cleaned data frame shape is (361, 5)

2. Filling missing data

In [62]:
# This looks better. I will anyhow use the subset data frame and assign NaN values "Unknown". I use copy of the subset_df
filled_df = subset_df.copy()
# Filling the missing values with "Unknown"
filled_df = filled_df.fillna('Unknown')
print(f"Filled data frame shape is {filled_df.shape}")

Filled data frame shape is (500, 5)

In [63]:
# Printing out the first 5 rows
filled_df.head()

   Object ID                         Title  Culture Object Date  Country
0          1  One-dollar Liberty Head Coin  Unknown        1853  Unknown
1          2  Ten-dollar Liberty Head Coin  Unknown        1901  Unknown
2          3    Two-and-a-Half Dollar Coin  Unknown     1909–27  Unknown
3          4    Two-and-a-Half Dollar Coin  Unknown     1909–27  Unknown
4          5    Two-and-a-Half Dollar Coin  Unknown     1909–27  Unknown

3. Discretization and Binning

In [65]:
# checking on how many rows are available
import numpy as np
met_large_df = pd.read_csv(file_path, low_memory=False)
met_large_df.shape

(484956, 54)

In [66]:
# Choosing only 10000 rows and selection of columns: Object Id, Title, object beginning data, and object end date to demonstrate binning
met_df = pd.read_csv(file_path, nrows=10000, low_memory=False)
# Choosing the selected columns for the task, and making sure there is no missing data
limited_df = met_df[['Object ID', 'Title', 'Object Begin Date', 'Object End Date']].dropna()
limited_df.shape

(10000, 4)

In [67]:
# Defining bin edges for equal-width - 1000 years
min_year = int(limited_df['Object Begin Date'].min())
max_year = int(limited_df['Object End Date'].max())
bins = range(min_year, max_year + 1000, 1000)

# Creating labels
labels = [f"{i}-{i+999}" for i in bins[:-1]]

# Applying the cut function
limited_df['Date Range Group'] = pd.cut(
    limited_df['Object Begin Date'],
    bins=bins,
    labels=labels,
    include_lowest=True
)

limited_df[['Object Begin Date', 'Date Range Group']].head()

   Object Begin Date Date Range Group
0               1853         995-1994
1               1901         995-1994
2               1909         995-1994
3               1909         995-1994
4               1909         995-1994

In [69]:
# Creating customized bins

# Defining customized bins
custom_bins = [-5000, 0, 1500, 1800, 1950, 2050]
age_labels = ['Ancient', 'Pre-Industrial', 'Industrial Era', 'Modern', 'Contemporary']

limited_df['Historical Era'] = pd.cut(
    limited_df['Object End Date'], 
    bins=custom_bins, 
    labels=age_labels,
    include_lowest=True
)

limited_df[['Object End Date', 'Historical Era']].head()

   Object End Date Historical Era
0             1853         Modern
1             1901         Modern
2             1927         Modern
3             1927         Modern
4             1927         Modern

### Chapter 8
1. Create hierarchical index  
2. Combine and Merge Datasets (you will have to either create a new dataset from your existing data or create a relationship between the data I have provided)   
3. Reshape   
4. Pivot the data

1. Create a hierarchical index

In [77]:
# Using Historical Era and Object ID to create a hierarchical index
hierarchical_df = limited_df.set_index(['Historical Era', 'Object ID'])

# Displaying the first five rows

hierarchical_df[['Title', 'Object End Date']].head(5)

                                                 Title  Object End Date
Historical Era Object ID
Modern         1          One-dollar Liberty Head Coin             1853
               2          Ten-dollar Liberty Head Coin             1901
               3            Two-and-a-Half Dollar Coin             1927
               4            Two-and-a-Half Dollar Coin             1927
               5            Two-and-a-Half Dollar Coin             1927

In [82]:
# Query data to see if there is data in the Ancient level in the hierarchical index
ancient_items = hierarchical_df.loc[['Ancient']].reset_index()
ancient_items[['Historical Era', 'Title', 'Object End Date']].head()

  Historical Era   Title  Object End Date
0        Ancient  Ribbon                0
1        Ancient   Frame                0

2. Combine and Merge Datasets (you will have to either create a new dataset from your existing data or create a relationship between the data I have provided)

In [87]:
# Creating Subset 1: Identifiers and Titles
df1 = limited_df[['Object ID', 'Title']].head(50)

# Creating Subset 2: Object Dates
df2 = limited_df[['Object ID', 'Object Begin Date', 'Object End Date']].head(50)

df1.head(5)

   Object ID                         Title
0          1  One-dollar Liberty Head Coin
1          2  Ten-dollar Liberty Head Coin
2          3    Two-and-a-Half Dollar Coin
3          4    Two-and-a-Half Dollar Coin
4          5    Two-and-a-Half Dollar Coin

In [88]:
df2.head(5)

   Object ID  Object Begin Date  Object End Date
0          1               1853             1853
1          2               1901             1901
2          3               1909             1927
3          4               1909             1927
4          5               1909             1927

In [89]:
# Merging the two datasets back together on Object ID
merged_df = pd.merge(df1, df2, on='Object ID', how='inner')

print("Merged Dataset Shape")
print(merged_df.shape)
merged_df.head()

Merged Dataset Shape
(50, 4)

   Object ID                         Title  Object Begin Date  Object End Date
0          1  One-dollar Liberty Head Coin               1853             1853
1          2  Ten-dollar Liberty Head Coin               1901             1901
2          3    Two-and-a-Half Dollar Coin               1909             1927
3          4    Two-and-a-Half Dollar Coin               1909             1927
4          5    Two-and-a-Half Dollar Coin               1909             1927

3. Reshape

In [91]:
# Using melt to reshape the data.
melted_df = pd.melt(
    limited_df.head(50), 
    id_vars=['Object ID', 'Title'], 
    value_vars=['Object Begin Date', 'Object End Date'],
    var_name='Date Type', 
    value_name='Year'
)

print("Melted/Reshaped Dataset")
melted_df.head()

Melted/Reshaped Dataset

   Object ID                         Title          Date Type  Year
0          1  One-dollar Liberty Head Coin  Object Begin Date  1853
1          2  Ten-dollar Liberty Head Coin  Object Begin Date  1901
2          3    Two-and-a-Half Dollar Coin  Object Begin Date  1909
3          4    Two-and-a-Half Dollar Coin  Object Begin Date  1909
4          5    Two-and-a-Half Dollar Coin  Object Begin Date  1909

4. Pivot the data

In [94]:
print(limited_df.columns)

Index(['Object ID', 'Title', 'Object Begin Date', 'Object End Date',
       'Date Range Group', 'Historical Era'],
      dtype='str')

In [100]:
# Creating a temporary subset to avoid index duplicates for pivoting
pivot_subset = limited_df.head(50).copy()

# Ensure Object ID is unique for the pivot
pivot_df = pivot_subset.pivot(
    index= 'Object ID', 
    columns='Historical Era', 
    values='Object End Date'
)

print("Pivoted Data Table Last rows out of 50")
pivot_df.tail()

Pivoted Data Table Last rows out of 50

Historical Era  Modern  Industrial Era
Object ID
46                 NaN          1800.0
47                 NaN          1800.0
48                 NaN          1800.0
49                 NaN          1800.0
50                 NaN          1800.0

### Chapter 10


Grouping with Dicts/Series   
Grouping with Functions   
Grouping with Index Levels   
Split/Apply/Combine    
Cross Tabs

### Chapter 11


Convert between string and date time   
Generate date range   
Frequencies and date offsets   
Convert timestamps to periods and back   
Period Frequency conversions