In [1]:
import numpy as np 

import pandas as pd 

import matplotlib.pyplot as plt 

df_missing = pd.read_excel("../datasets/Sample - Superstore.xls",sheet_name="Missing") 
df_missing.head()

             Customer  Product     Sales  Quantity  Discount   Profit
0     Brosina Hoffman      NaN  1706.184       9.0       0.2  85.3092
1     Brosina Hoffman   Phones   911.424       4.0       0.2  68.3568
2  Zuschuss Donatelli      Art     8.560       2.0       0.0   2.4824
3  Zuschuss Donatelli   Phones       NaN       3.0       0.2  16.0110
4  Zuschuss Donatelli  Binders    22.720       4.0       0.2   7.3840

In [2]:
df_missing.fillna('FILL')

              Customer      Product     Sales Quantity  Discount   Profit
0      Brosina Hoffman         FILL  1706.184      9.0       0.2  85.3092
1      Brosina Hoffman       Phones   911.424      4.0       0.2  68.3568
2   Zuschuss Donatelli          Art      8.56      2.0       0.0   2.4824
3   Zuschuss Donatelli       Phones      FILL      3.0       0.2   16.011
4   Zuschuss Donatelli      Binders     22.72      4.0       0.2    7.384
5        Eric Hoffmann      Binders    11.648     FILL       0.2   4.2224
6        Eric Hoffmann  Accessories     90.57      3.0       0.0  11.7741
7         Ruben Ausman         FILL     77.88      2.0       0.0     FILL
8                 FILL  Accessories     13.98      2.0       0.0   6.1512
9         Kunst Miller      Binders    25.824      6.0       0.2   9.3612
10        Kunst Miller        Paper    146.73      3.0       0.0  68.9631

In [3]:
df_missing[['Customer','Product']].fillna('FILL')

              Customer      Product
0      Brosina Hoffman         FILL
1      Brosina Hoffman       Phones
2   Zuschuss Donatelli          Art
3   Zuschuss Donatelli       Phones
4   Zuschuss Donatelli      Binders
5        Eric Hoffmann      Binders
6        Eric Hoffmann  Accessories
7         Ruben Ausman         FILL
8                 FILL  Accessories
9         Kunst Miller      Binders
10        Kunst Miller        Paper

In [6]:
# df_missing['Sales'].fillna(method='ffill') #caused an error
df_missing['Sales'].ffill()

0     1706.184
1      911.424
2        8.560
3        8.560
4       22.720
5       11.648
6       90.570
7       77.880
8       13.980
9       25.824
10     146.730
Name: Sales, dtype: float64

In [9]:
# df_missing['Sales'].fillna(method='bfill') 
df_missing['Sales'].bfill()

0     1706.184
1      911.424
2        8.560
3       22.720
4       22.720
5       11.648
6       90.570
7       77.880
8       13.980
9       25.824
10     146.730
Name: Sales, dtype: float64

In [14]:
sales_mean = df_missing['Sales'].mean()
df_missing['Sales'] = df_missing['Sales'].fillna(sales_mean) 
df_missing['Sales']

0     1706.184
1      911.424
2        8.560
3      301.552
4       22.720
5       11.648
6       90.570
7       77.880
8       13.980
9       25.824
10     146.730
Name: Sales, dtype: float64